### ISSUE TITLE
Best interface?

### ISSUE THREAD

**Issue by ChristianFranke** [node-dmx/dmx#125]
I am currently looking for a DMX USB interface. Which one is the best according to your research? 

For me it is better to invest a little more money. But then the interface must be able to control multiple channels simultaneously without jerks.

**Comment by hrueger** [comment]
Hi @ChristianFranke,
I can tell you what I have tried so far. However, please not that I'm only a student and not a professional lighting engineer ;-)

I started out with a [Chamsys Magic DMX Basic](https://chamsyslighting.com/products/magicdmx-basic-de) beacuse it is very cheap (it cost me around 20 bucks). However, it is only compatible with the MagicQ software and as you're here on the Node DMX library that's probably not what you are looking for ;-)

For the last 3 years I've been using an [Enttec USB DMX Pro Mk2](https://www.enttec.com/product/controls/dmx-usb-interfaces/dmx-usb-pro-interface/) and very happy with it. I have only used Universe 1, but the interface offers 2 universes OUT and 1 universe IN.
It has been very stable and never crashed. I didn't have any issues with it.

However, I'd recommend looking into ARTNET interfaces, because almost every software can output ARTNET. In addition, it is IP based, so it can be anywhere on your network, and doesn't have to be connected directly to your computer via USB. In my opinion, that's a big advantage, but I don't know if you always have a network where you want to use the interface.

Maybe it is also interesting to note that Artnet can (although it is not recommended) be transmitted via WiFi, so if you have a Tablet / Laptop / Convertible, you could walk around the room and still control your fixtures.

I hope that helps!
